version: '3.7'
services:
  db:
    image: mariadb:10.10
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  redis:
    image: redis:6.0
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
