env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: __dirname
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "react"
  - "jest"
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/unbound-method": [ "off" ]
  "jest/unbound-method": [
    "error",
    {
      "ignoreStatic": true
    }
  ]
  "no-unused-vars": "off"
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/no-unused-vars": "error"
settings:
  react:
    version: "17.0"
